# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [ pre-commit ]
default_install_hook_types: [ pre-commit, commit-msg ]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        name: LF for all files
        args: [ --fix=lf ]
        exclude: '\.bat$'
      - id: mixed-line-ending
        name: CRLF for windows scripts
        args: [ --fix=crlf ]
        files: '\.bat$'
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [ --assume-in-merge ]
      - id: file-contents-sorter
        name: Sort and deduplicate spellcheck whitelist
        files: (^|/)whitelist\.txt$
        args: [ --unique ]

  # TOML files
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: ade0f95ddcf661c697d4670d2cfcbe95d0048a0a  # frozen: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 5b5dddc4fb0f83c3ea1fc5616fa63e115dce83e0  # frozen: v0.49.1
    hooks:
      - id: markdownlint
        files: \.md$
        exclude: CHANGELOG\.md
        args: [ --fix ]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: [ --strict, -c=.yamllint ]

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: 805f85e558841bf4d852335e036b33d2b26be1cc  # frozen: v1.7.12.25
    hooks:
      - id: actionlint

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8  # frozen: v1.5.6
    hooks:
      - id: insert-license  # Insert a short license disclaimer as a header comment in source files
        files: \.py$
        args:
          - --license-filepath
          - .copyright-header.txt
          - --use-current-year

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2eeb5678de71a00c0902cbda7105d328432f72cb  # frozen: v0.16.8
    hooks:
      - id: ruff-check
        args: [ --fix, --exit-non-zero-on-fix, --extend-fixable=F401 ]
      - id: ruff-format

  - repo: https://github.com/PyCQA/flake8
    rev: 7eccf20b526fe4f2230bf9afeeef2fc9f97faf8d  # frozen: 7.4.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject==1.2.4
          - flake8-spellcheck==0.28.0
          - flake8-qgis==2.1.0

  - repo: https://github.com/PyCQA/bandit
    rev: 92ae8b82fb422a639f0ed8d99e96cea769594e08  # frozen: 1.9.4
    hooks:
      - id: bandit
        args: [ -c, pyproject.toml ]

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: 6972e4c5a7e9f45f05a2f30b668f221f43b770c9  # frozen: v0.0.84
    hooks:
      - id: ty

  - repo: https://github.com/nlsfi/qgis-plugin-dev-tools
    rev: 5bedbcb39455262e5e1aed1e5ca5e9f14928799f  # frozen: v0.13.2
    hooks:
      - id: update-translations
      - id: normalize-xml

  # commit-msg hooks
  # Commit messages should follow [Conventional Commits notation](https://www.conventionalcommits.org/en/v1.0.0/#summary).
  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98  # frozen: v0.19.1
    hooks:
      - id: gitlint
        stages: [ commit-msg ]
