# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
default_install_hook_types: [pre-commit, commit-msg]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        name: LF for all files
        args: [--fix=lf]
        exclude: '\.bat$'
      - id: mixed-line-ending
        name: CRLF for windows scripts
        args: [--fix=crlf]
        files: '\.bat$'
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
        args: [--assume-in-merge]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license  # Insert a short license disclaimer as a header comment in source files
        files: \.py$
        args:
          - --license-filepath
          - copyright-header.txt
          - --use-current-year

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
        args: [ --fix, --exit-non-zero-on-fix, --extend-fixable=F401 ]
      - id: ruff-format

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject==1.2.4
          - flake8-spellcheck==0.28.0
          - flake8-qgis==2.0.1

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev:  v2.3.1
    hooks:
      - id: mypy
        additional_dependencies:
          - PyQt5-stubs==5.15.6.0

  # - repo: https://github.com/nlsfi/qgis-plugin-dev-tools
  #   rev: v0.13.1
  #   hooks:
  #     - id: update-translations

  # commit-msg hooks
  # Commit messages should follow [Conventional Commits notation](https://www.conventionalcommits.org/en/v1.0.0/#summary).
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [ commit-msg ]
